export const BACKEND_PORT = 5005
export const API = `http://localhost:${BACKEND_PORT}`;
export const TOKEN_KEY = "token";
export const USER_KEY = "user";
export const USER_DETAIL_KEY = "userDetail";
export const THREAD_KEY = "userThread";
export const COMMENT_KEY = "userComment";
export const THREAD_CACHE_KEY = 'threadCache';
export const threadTime = 10 * 1000; //cached thread expired every 10s